### ISSUE TITLE
Implement also a different directory layout

### ISSUE THREAD

**Issue by wickedpuppy** [NitzanHen/agrippa#27]
Some people adopt this directory layout:
```
components
    └── MyComponent
        ├── MyComponent.tsx
        └── index.js
```

MyComponent.tsx holds the component's code and index.js is always something like:

`export {default} from './MyComponent.tsx'`

That directory layout allows to group files related to MyComponent inside its directory, helps identify what component we are working on in the editor (when you have 10 files called index.tsx open you get confused), and keeps a clean import syntax, such as:

`import MyComponent from '../MyComponent'`

Are you interested in implementing such a feature?

I could do it :-)

**Comment by NitzanHen** [comment]
Implemented in PR #31; this will be added to the next minor version of Agrippa, v1.3.0.

Thanks again for suggesting this feature!
