### ISSUE TITLE
Add support for this component file structure

### ISSUE THREAD

**Issue by NitzanHen** [NitzanHen/agrippa#42]
> This is a good suggestion! I want to use Agrippa, but we have a component file structure that I can't create with Agrippa.
> 
> Below is the default structure of each component. I have a template folder on my desktop that I just copy when I want to create a new component.
> 
> **Folder structure** `src/components/component-name`
> 
> **Content of a component**
> 
> ```
> component-name.interfaces.ts
> component-name.styles.ts
> component-name.tsx
> index.ts
> ```
> 
> ### File content
> 
> **component-name.interfaces.ts**
> 
> ```
> export interface OptionalStyleProps {
> }
> 
> export interface RequiredStyleProps {
> }
> 
> export interface ComponentProps {
> }
> 
> export interface Props
>   extends ComponentProps,
>     Partial<RequiredStyleProps>,
>     OptionalStyleProps {}
> ```
> 
> **component-name.styles.ts**
> 
> ```
> import tw from 'twin.macro'
> export const StyledComponentName = tw.div``
> ```
> 
> **component-name.tsx**
> 
> ```
> import { Props } from './component-name.interfaces'
> import { StyledComponentName } from './component-name.styles'
> 
> /**
>  * Primary UI component for user interaction
>  */
> export function ComponentName(props: Props) {
>   return (
>     <StyledComponentName>
>       {children}
>     </StyledComponentName>
>   )
> }
> ```
> 
> **index.ts**
> 
> ```
> export * from './component-name'
> export type { Props as ComponentNameProps } from './component-name.interfaces'
> ```
> 
> Would it be possible to add support for some configuration so that Agrippa could generate something this?

(Quote is a reply on #2 by @nonameolsson)

**Comment by NitzanHen** [comment]
Hi @nonameolsson,
I think the direction Agrippa is going in right now is towards more flexibility, with the aim that developers or teams with a specific desired component file structure (like you!) could configure Agrippa to generate their exact structure. 

This will probably take a while to implement well, and unfortunately I don't have an estimate.
However, I think for the meantime you could probably achieve a good result using post commands.
I'll try to elaborate; feel free to also take a look at [Post Command cookbook 🍲](https://github.com/NitzanHen/agrippa/wiki/Post-Command-cookbook-%F0%9F%8D%B2).

**Comment by NitzanHen** [comment]
Post commands, in short, allow you to run any command after generating a component; these commands can also use the paths of generated files, which Agrippa supplies when it actually runs them.
In your case, it seems that you'd need not only paths, but also the component name - I'll try to get a special beta version for that soon. 

The post-command itself should probably run a script - a batch file, a shell script, a JS script, or something else, depending on whether you're using Windows or Linux and what you're most comfortable with. 
If you're comfortable with writing a script on your own - go for it! and share your results so that others may have a good example.
Otherwise, we can try and form it together - are you using Windows or Linux? would you prefer writing a JS script?

Some points to consider:
- For Agrippa, use `props`: `none` and `styling`: `none` (since you'd be creating them in the post command), and `declaration`: `function`.
- Your `component-name.interfaces.ts` seems static, aside from its name - in which case you only need to copy it to `<component-name>.interfaces.ts`.
- For your styles file, you need to write 
```js
import tw from 'twin.macro'
export const Styled<ComponentName> = tw.div``
```
into `<component-name>.styles.ts`. 
- For your index file, you'd need to append the line `export type { Props as <ComponentName>Props } from './<component-name>.interfaces'` to the existing index file.
- Lastly, for the main file, you'd need to prepend `import { Props } from './<component-name>.interfaces'` as the first line, and replace `<ComponentName>(props)` with `<ComponentName>(props: Props)`.

Each of these maps to a simple command or two in batch/shell scripts, as far as I know; in JS it might be a little more cumbersome, but still not too much (mostly just calling `fs` commands and dealing with arguments). 

What do you say?

**Comment by NitzanHen** [comment]
> In your case, it seems that you'd need not only paths, but also the component name - I'll try to get a special beta version for that soon.

Published - It'll be officially out in v1.4.0, but for now you can install it using `npm i -g agrippa@1.4.0-alpha.2`.
This is technically an unstable version - but all tests pass as usual, and the new feature seems to work smoothly. Either way, if you come across a bug, please report it!

**Comment by nonameolsson** [comment]
Wow, thank you for taking the time to explain this. It looks like an interesting approach! I will try to play with it and let you know how it turns out 👍🏻

**Comment by coronary** [comment]
For anyone interested I wrote up a little script which uses the `v1.3.1` release. I pass the `<dirPath>` to the postCommand script and use awk to extract the component name. This script was written just for my specific use case so you'll probably need to tweak it. I'm developing in react native and my file structure after calling this script in a postCommand looks like
```
Component.tsx
Component.styles.ts
Component.types.ts
index.ts
```
feel free to take it and tweak it however you want to fit your needs.

### script assumptions:
- styling:none
- props:ts
- passed one argument `<dirPath>`

```bash
# Setup component variables
componentName=$(echo $1 | awk 'BEGIN {FS = "/"}; {print $(NF)}')
componentPath="$1/${componentName}.tsx"

# Creates external 'types' file with exported componentNameProps interface
propsInterface="${componentName}Props"
typesFile="export interface $propsInterface {};"
typesPath="$1/$componentName.types.ts"
echo $typesFile > $typesPath

# Creates external 'style' file that exports Stylesheet called 'styles'
stylesFile="import { StyleSheet } from 'react-native';\n\nexport const styles = StyleSheet.create({});"
stylesPath="$1/$componentName.styles.ts"
echo $stylesFile > $stylesPath

# Replaces original prop interface export with import from new 'style' and 'type' files
typeImport="import { $propsInterface } from './$componentName.types';"
stylesImport="import { styles } from './$componentName.styles';"
# if not on osx or this sed command doesn't work remove the "" from after the i flag
sed -i "" "s|^export interface.*|$typeImport\n$stylesImport|g" $componentPath
```

### file outputs
TestComponent.tsx
```typescript
import React from 'react';
import { View } from 'react-native';

import { TestCompProps } from './TestComp.types';
import { styles } from './TestComp.styles';

export const TestComp: React.VFC<TestCompProps> = () => {
	
	return (
		<View></View>
	);
};
```
TestComponent.types.ts
```typescript
export interface TestCompProps {};
```
TestComponent.styles.ts
```typescript
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({});
```
index.ts (unmodified)

**Comment by NitzanHen** [comment]
@coronary amazing!

**Comment by NitzanHen** [comment]
Closing this issue. @nonameolsson, I'm hoping you managed to find a solution (if not, please reply!)

I'm pinning this issue, as the workaround of using post-commands, as well as @coronary example, can be helpful in other, similar cases that other devs might come across.

As I've mentioned, Agrippa is going I'm the direction of greater flexibility for custom stacks and file structures. However, it will probably be a while before it's implemented, so for now this workaround is important.

@nonameolsson, thanks again for reaching out, and @coronary thanks for your great example.
