### ISSUE TITLE
Generate a tsx component even without using TypeScript

### ISSUE THREAD

**Issue by nsebhastian** [NitzanHen/agrippa#5]
Hi, I'm trying to generate a component with Agrippa using the following command:

```
agrippa gen button
```

The result is that the CLI generated an `index.tsx` file in the `Button/` folder as follows:

```
[INFO]: Generation successful.
[INFO]: Generated files:
[INFO]: /Sandbox/example-app/src/Button/index.tsx
[INFO]: /Sandbox/example-app/src/Button
```

Isn't it supposed to generate an `index.jsx` or `index.js` file for the component? I'm currently on a fresh create-react-app install without a `tsconfig.json` file in the application.

Is there something I'm missing? 

Thanks!

**Comment by nsebhastian** [comment]
Hi @NitzanHen 

I just did a further debug with the `--debug` option and it seems `--typescript` option is set to `true` even when `tsconfig.json` is not found.

Take a look at the following output from the `--debug` command:
```
agrippa gen button --debug true
[DEBUG]: Agrippa v1.1.0
[DEBUG]: Looking for tsconfig.json...
[DEBUG]: Looking for .agripparc.json...
[DEBUG]: Looking for .package.json...
_[DEBUG]: No tsconfig.js found._
[DEBUG]: .agripparc.json found!
[DEBUG]: path: /Users/nsebhastian/Desktop/Sandbox/example-app/.agripparc.json
[DEBUG]: config: { styling: 'css', props: 'none' }
[DEBUG]: package.json found!
[DEBUG]: path: /Users/nsebhastian/Desktop/Sandbox/example-app/package.json
[DEBUG]: content: {
  name: 'example-app',
  version: '0.1.0',
  private: true,
  dependencies: {
    '@testing-library/jest-dom': '^5.11.4',
    '@testing-library/react': '^11.1.0',
    '@testing-library/user-event': '^12.1.10',
    react: '^17.0.2',
    'react-dom': '^17.0.2',
    'react-scripts': '4.0.3',
    'web-vitals': '^1.0.1'
  },
  scripts: {
    start: 'react-scripts start',
    build: 'react-scripts build',
    test: 'react-scripts test',
    eject: 'react-scripts eject'
  },
  eslintConfig: { extends: [ 'react-app', 'react-app/jest' ] },
  browserslist: {
    production: [ '>0.2%', 'not dead', 'not op_mini all' ],
    development: [
      'last 1 chrome version',
      'last 1 firefox version',
      'last 1 safari version'
    ]
  }
}
[DEBUG]: baseDir option, before resolving, is undefined
[DEBUG]: No baseDir specified, resolving relative to cwd
[DEBUG]: Generating component...
[DEBUG]: config: {
  name: 'button',
  debug: true,
  styling: 'css',
  props: 'none',
  children: false,
  _typescript: true,_
  flat: false,
  overwrite: false,
  destination: '.',
  stylingModule: true,
  importReact: true,
  postCommand: undefined,
  baseDir: '/Users/nsebhastian/Desktop/Sandbox/example-app/src',
  allowOutsideBase: false
}
```

As you can see, the output says `No tsconfig.js found` but `typescript: true` just below the `Generating component...` line

**Comment by NitzanHen** [comment]
(I closed this by mistake, sorry.)

Thank you for reporting this awkward bug! You're most correct, if a `tsconfig.json` file is not found, the project is assumed to be Javascript by default, and `jsx` files should be generated.  

This should be fixed in [v1.1.1](https://github.com/NitzanHen/agrippa/releases/tag/v1.1.1); I've fixed two other, small bugs along the way. Please test it out!

Also, your included `debug` output sent me in the right direction, so thanks again!

**Comment by nsebhastian** [comment]
Hello, 

Yeah, I see the bug has been fixed now. Thanks for the quick response!

By the way, I also wrote an article about Agrippa here:

https://blog.bitsrc.io/create-react-components-from-the-command-line-with-agrippa-621a6f4d19e8

I hope more people know about this tool because it's very useful 👍

**Comment by NitzanHen** [comment]
Your article is great! Thank you for writing about Agrippa!
