### ISSUE TITLE
Consider making an NX plugin

### ISSUE THREAD

**Issue by gioragutt** [NitzanHen/agrippa#8]
Hey @NitzanHen, congrats on the nice tool, great initiative!

Since you obviously like code-generation, I suggest you look at https://github.com/nrwl/nx.

It's a tool for mono-repos, but at its core is code generation.

Extending your tool to also be a plugin for NX and allowing NX users to use it can help you gain users for your tool 👍🏻

**Comment by NitzanHen** [comment]
Hi! thanks a lot!

I'd actually heard of Nx before, but have never got the chance to really pick it up. I'll look into it! 

In general terms, what would you say that an Nx plugin can do (in the context of React component generation and such) that could make Agrippa better for Nx users?

**Comment by npalladium** [comment]
This is a really great tool! Kudos and thanks! 🎉 

Haven't used nx much and only with Angular, so I might be off base. `nx generate` (and similar commands) are an abstraction over other _generators_ that can be provided as a plugin. For example `nx generate @nrwl/angular:component name-here` could be used to generate a component with the `@nrwl/angular:component` generator. 

Having agrippa as a plugin might make it easier for those using Nx.

**Comment by NitzanHen** [comment]
Thanks a lot!!

I'll be sure to find time to look into Nx as a whole and creating a plugin particularly.

If you (or anyone else) have any further ideas regarding what an `nx-agrippa` plugin can do, or how to do it, be sure to write them here!

**Comment by NitzanHen** [comment]
Closing this issue. 
I am not familiar with Nx, sadly and do not have currently the time to learn how to develop plugins for it (as well as create and maintain one). 

If anyone else wants to pick this up, go for it! I'd be grateful. This probably belongs on its own repo, though. 

Thanks again for reaching out.
