### ISSUE TITLE
What to do with not existing properties in docs but existing in JSON schema?

### ISSUE THREAD

**Issue by EmilySeville7cfg** [NitzanHen/agrippa#88]
There are some properties mentioned in [JSON schema](https://github.com/SchemaStore/schemastore/pull/2638) but missing from [docs](https://www.agrippa.dev/reference/config-options/):

- `props`
- `children`
- `flat`
- `stylingModule`
- `postCommand`
- `destination`
- `tsPropsDeclaration`
- `memo`
- `separateIndex`
- `reactNative`

What I have to do with them? Remove?

**Comment by NitzanHen** [comment]
Hi!

The JSON schema was used in older versions of Agrippa, up to v1.4, while the docs refer to Agrippa v2.0 (and will be updated whenever Agrippa is).

I highly recommend updating to Agrippa 2.0; if you can't, I can try to search for an old version of the docs (that were hosted here, on a GitHub Wiki) that might be helpful to you.

Thanks for reaching out
